### PR TITLE
Correct CSV content type

### PR DESCRIPTION
**Pull request by tekin**
The CSV content type is incorrect according to the [IANA Media Type Registry](https://www.iana.org/assignments/media-types/media-types.xhtml#text). This corrects it to be `"text/csv"` rather than `"text/comma-separated-values"`.

### CODE REVIEW

**Comment by halostatue** [comment]
I can’t accept this change as the JSON dictionary is not the source data (as noted in [Contributing](https://github.com/halostatue/mime-types/blob/master/Contributing.rdoc#adding-or-modifying-mime-types)). The file that you’re looking for is `type-lists/text.yml`. Modify that and revert the `.json` back and we can get this merged. I’ll probably look at getting a release out with this correction nearer the end of the month.

**Comment by tekin** [comment]
Apologies, totally failed to read the Contributing doc.

Having now looked at [text.yml](https://github.com/halostatue/mime-types/blob/master/type-lists/text.yaml), it looks like the problem I'm experiencing is elsewhere - there are two matching `MIME::Type` for the csv extension, one of which is marked as obsolete and the [code in question](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/processing/mime_types.rb#L62) is simply picking the first one, which in v2 of the mime-types gem happens to be the obsolete one. Closing this as the fix is to make sure carrierwave doesn't choose an obsolete type over a non-obsolete one. Thanks.

**Comment by halostatue** [comment]
No problem. I think there’s a bug around this that needs to be fixed. In the short term, it *may* be possible to try this with a reordering of `text.yml` to put the obsolete one *last*—but `MIME::Type#priority_order` should be taking care of that.

**Comment by tekin** [comment]
It seems to fall down with the first check in `MIME::Type#priority_order` - the comparison of `#simplified` is `"text/comma-separated-values" <=> "text/csv"`.

**Comment by ypresto** [comment]
Same issue here. `priority_compare` should return "text/csv" which is `use_instead` of "text/comma-separated-values".

**Comment by aprescott** [comment]
I encountered this issue because `MIME::Types.of("csv").first` is coming back with `text/comma-separated-values`, instead of the expected `text/csv`. This causes an issue with [libraries like Shrine](https://github.com/janko-m/shrine/blob/5a3c6b59eca9dbf4d79a6a75a6bc801937222856/lib/shrine/plugins/determine_mime_type.rb#L204), where an application has less control over how the mime type look-up happens. I think it'd be great to prioritize types whose `registered?` value is `true`, over others where it's `false`.

**Pull request closed without merging**
